/**
 * Prompt tests: version pinning, embedding-safety (no backticks, no
 * interpolation markers), required content, and byte-for-byte sync with the
 * review markdown generated by scripts/gen-prompt-md.ts.
 */
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import assert from "node:assert/strict";
import test from "node:test";

import {
  buildGoalDiscoveryUserPrompt,
  GOAL_DISCOVERY_SYSTEM_PROMPT,
  PROMPT_VERSION,
} from "../lib/goal-discovery/prompt";

const promptMdPath = resolve(__dirname, "../../docs/ai/prompts/goal-discovery.v1.md");

test("PROMPT_VERSION is pinned", () => {
  assert.equal(PROMPT_VERSION, "goal-discovery.v1");
});

test("system prompt contains no backticks (markdown-fence safe)", () => {
  assert.ok(!GOAL_DISCOVERY_SYSTEM_PROMPT.includes("`"));
});

test("system prompt contains no template interpolation markers", () => {
  assert.ok(!GOAL_DISCOVERY_SYSTEM_PROMPT.includes("${"));
});

test("system prompt pins the key contract semantics", () => {
  for (const fragment of [
    "boss-contract.v0",
    "recordKind: LIVE",
    "status: DRAFT",
    "revision: 1",
    "NOT_STARTED",
    "UNKNOWN",
    "CREATE_NEW_BOSS",
    "LOG_INSPECTED",
    "evidenceItems, blockers, changeHistory: empty arrays",
    "copied VERBATIM",
  ]) {
    assert.ok(
      GOAL_DISCOVERY_SYSTEM_PROMPT.includes(fragment),
      `prompt must mention: ${fragment}`,
    );
  }
});

test("user prompt wraps the goal in the request envelope", () => {
  const payload = JSON.parse(buildGoalDiscoveryUserPrompt("我的目标")) as { schemaVersion: string; goal: string };
  assert.equal(payload.schemaVersion, "boss-contract.v0");
  assert.equal(payload.goal, "我的目标");
});

test("generated markdown fenced block matches the runtime prompt byte for byte", () => {
  const markdown = readFileSync(promptMdPath, "utf-8");
  const match = markdown.match(/```\n([\s\S]*?)\n```/);
  assert.ok(match, "docs/ai/prompts/goal-discovery.v1.md must contain a fenced block");
  if (match![1] !== GOAL_DISCOVERY_SYSTEM_PROMPT) {
    console.error(
      "Prompt drift detected. Regenerate with: node --import tsx scripts/gen-prompt-md.ts",
    );
  }
  assert.equal(match![1], GOAL_DISCOVERY_SYSTEM_PROMPT);
});
